// Create a class Employee having private instance member 
// id- id is readonly property and generated by your application
// name- write getter setter
// salary- write getter setter
// net salary
// Write method who’s job is to deduct TDS 10% and return tax amount and set netsalary instance member after deducting tax.
// Declare TDS as static variable.
// Your application should create only 3 object if you try to create 4th object it should throw exception.
// Give appropriate validation like salary can not be 0 or negative, maximum
// Salary allowed is 50000 if you try to set more then 50000 it should give some error message.
// When you run your application it should print name of company.

class Employee{
    int id;
    static int getId;
    static double TDS =10;
    string name;
    double salary,netsalary,taxAmount;

    static Employee(){
        Console.WriteLine("Welcome to Artic901 pvt ltd.");
    }
    public Employee(string name,double salary){

        if(getId>2){
            throw new Exception("Cannot create another Object");
        }
        id=++getId;
        Name=name;
        Salary=salary;
    }

    public int Id{
        get{return id;}
    }
    public string Name{
        get{return name;}
        set{name=value;}
    }

    public double Salary{
        get{return salary;}
        set{
            if(value<=0 || value>50000){
                throw new Exception("Salary must be in between 0 and 50000");
            }            
            salary=value;
        }
    }
    public double CalculateNetSal()
        {
            netsalary = salary - salary * (TDS / 100);
            return netsalary;
        }

    public double payTDS() {
            CalculateNetSal();
            taxAmount = salary * (TDS /100); 
            return taxAmount;
    }

    public override string ToString(){
        return string.Format("id={0} name={1} Salary={2} netSalary={3} taxAmount={4}",id,name,salary,netsalary,taxAmount);
    }

     public class Program{
            static void Main(string[] args){
                try{

                Employee e1=new Employee("Tejas",20000);
                e1.CalculateNetSal();
                e1.payTDS();
                Console.WriteLine(e1);
                Employee e2=new Employee("Saurabh",30000);
                   e2.CalculateNetSal();
                e2.payTDS();
                Console.WriteLine(e2);
                Employee e3=new Employee("Pratik",40000);
                   e3.CalculateNetSal();
                e3.payTDS();
                Console.WriteLine(e3);
                Employee e4=new Employee("Yash",50000);
                }catch(Exception e){
                    Console.WriteLine(e.Message);
                }
            }
        }
}