
//Create a Account class having instance member
// id, firstname, LastName, MiddleName, bal. 
//Id should be generated by your application. 
//Interest rate for  account is 7%. 
//It has instance method 
//public void deposit(double amt) who’s job is to increase the instance balance.
//It has instance method 
//public void withdraw(double amt) who’s job is to reduce the instance balance
// It has static method payint(public static double payint(Account obj)) who’s job is to calculate interest of each saving account holder and increase balanace and retun interest amount. 
//Create instance method display who’s job is to display Name and bal. 
//Create 3 object of account class. As soon as application load it should display name of bank.
//Create 3 constructor let one constructor write logic to validate firstname can not be <3 character

using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.Text;
using System.Threading.Tasks;

namespace Account2
{
    class Account { 

        static int getid=1;
        int Id;
        static double interest_rate = 0.07;
        string firstname;
        string lastname;
        string midlename;
        double balance;
    static Account()
    {
        Console.WriteLine("Bank name : Bank of 901 Gringotts !!!!!!");
    }
    public Account(string firstname, string lastname, string midlename):this(firstname)
    {
        Id = getid++;
        this.lastname = lastname;
        this.midlename = midlename;


    }
    public Account(string firstname, string lastname)
    {
        Id = getid++;

        this.firstname = firstname;
        this.lastname = lastname;
    }

    private Account(string firstname)
        {
            int fin = firstname.Length;
            if (fin > 12 || fin < 3)
            {
                throw new Exception("First Name should be greater than 3 and must be less than 12");

            }
            else
            { 
                this.firstname = firstname;
            }
        }



    public void deposit(double amt)
    {
        balance = balance + amt;
    }
    public void withdraw(double amt)
    {
        if (amt>balance)
        {
            throw new Exception("Insufficient balance");
        }
        else
            balance = balance - amt;
    }
    public static double payint(Account obj)
    {
        double interest = interest_rate * obj.balance;
            obj.deposit(interest);
        return interest;
    }
    public string display()
    {
        return String.Format($"Account holder name : {firstname} {midlename} {lastname} \n Account holder id={Id}\n Balance={balance} ");
    }



}
internal class Program
{
    static void Main(string[] args)
    {

        try
        {
            Account a1 = new Account("tejas", "ghude", "chandrakant");
            Account a2 = new Account("Saurabh", "Phore");
            a1.deposit(500);
            a2.deposit(600);

            Console.WriteLine(a1.display());
            Account.payint(a1);
            Account.payint(a2);

            Console.WriteLine(a2.display());

        }
        catch (Exception e) { 
            Console.WriteLine(e.Message);
        }



    }
}
}
